services:
  - type: web
    name: assistente-pedro-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ZAPIER_WEBHOOK_URL
        value: https://hooks.zapier.com/hooks/catch/23093694/2jz0pr7/
